//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shagrir
    {
        public Shagrir()
        {
            this.Candidates = new HashSet<Candidate>();
            this.Sharings = new HashSet<Sharing>();
            this.Sharings1 = new HashSet<Sharing>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Reputation { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Gender { get; set; }
    
        public virtual ICollection<Candidate> Candidates { get; set; }
        public virtual ICollection<Sharing> Sharings { get; set; }
        public virtual ICollection<Sharing> Sharings1 { get; set; }
    }
}
